[build]
  base = "."
  publish = "dist/"
  command = "yarn build"

[[redirects]]
  from = "/api"
  to = "'https://dstzf5kmgfl76io5ynsn3yn7hm0gbeur.lambda-url.us-east-1.on.aws/:splat"
  status = 200
  force = true