[build]
  base = "."
  publish = "dist/"
  command = "yarn build"


[[redirects]]
  from = "/api/*"
  to = "https://nwjuct77lwx2v7zklxwsknijfu0gpdxb.lambda-url.us-east-1.on.aws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true